[package]
name = "rustJieba"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jieba-rs = "0.6"
wasm-bindgen = "0.2.61"
lazy_static = "1.2.0"
json = "0.12.4"